'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AddQuestion

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''QuestionsInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QuestionsInfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RadiobtnDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadiobtnDesc As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''RadiobtnMCQs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadiobtnMCQs As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''RadiobtnTFs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadiobtnTFs As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''TxtboxQuestionStatement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtboxQuestionStatement As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RadiobtnEasy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadiobtnEasy As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''RadiobtnMedium control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadiobtnMedium As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''RadiobtnDifficult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadiobtnDifficult As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''TxtboxMarks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtboxMarks As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SpaceOptionA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SpaceOptionA As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Txtbox_OptionATitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txtbox_OptionATitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Txtbox_OptionA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txtbox_OptionA As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SpaceOptionB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SpaceOptionB As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Txtbox_OptionBTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txtbox_OptionBTitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Txtbox_OptionB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txtbox_OptionB As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SpaceOptionC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SpaceOptionC As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Txtbox_OptionCTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txtbox_OptionCTitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Txtbox_OptionC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txtbox_OptionC As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SpaceOptionD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SpaceOptionD As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Txtbox_OptionDTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txtbox_OptionDTitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Txtbox_OptionD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txtbox_OptionD As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SpaceCorrectOption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SpaceCorrectOption As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Txtbox_CorrectOptionTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txtbox_CorrectOptionTitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Txtbox_CorrectOption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txtbox_CorrectOption As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SpaceTF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SpaceTF As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''TFradiobtn_title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TFradiobtn_title As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Radiobtn_TF_True control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Radiobtn_TF_True As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Radiobtn_TF_False control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Radiobtn_TF_False As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''BtnInsertQuestion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnInsertQuestion As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnClear As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ValidationSummary1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidationSummary1 As Global.System.Web.UI.WebControls.ValidationSummary

    '''<summary>
    '''Lbl_showErrorMessages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lbl_showErrorMessages As Global.System.Web.UI.WebControls.Label
End Class
