'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Setting

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''txtboxNumberOfQuestion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtboxNumberOfQuestion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''radiobtn_isQuestionShuffleTrue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radiobtn_isQuestionShuffleTrue As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''radiobtn_isQuestionShuffleFalse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radiobtn_isQuestionShuffleFalse As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''radiobtn_isAnswerShuffleTrue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radiobtn_isAnswerShuffleTrue As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''radiobtn_isAnswerShuffleFalse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radiobtn_isAnswerShuffleFalse As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtbox_startingTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbox_startingTime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtbox_QuizDuration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbox_QuizDuration As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtbox_NoOfQuestionToBeShown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbox_NoOfQuestionToBeShown As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''radiobtn_isNegativeMarkingTrue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radiobtn_isNegativeMarkingTrue As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''radiobtn_isNegativeMarkingFalse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radiobtn_isNegativeMarkingFalse As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''cmd_SaveSetting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmd_SaveSetting As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ValidationSummary1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidationSummary1 As Global.System.Web.UI.WebControls.ValidationSummary

    '''<summary>
    '''lbl_showErrorMessages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_showErrorMessages As Global.System.Web.UI.WebControls.Label
End Class
